#!/bin/bash
echo "🚀 启动开发服务器..."
echo ""
echo "请在四个不同的终端窗口分别执行："
echo ""
echo "终端1 - 总站门户:"
echo "  cd $(dirname $0)/portal && npm run docs:dev -- --port 3000"
echo ""
echo "终端2 - 个人知识库:"
echo "  cd $(dirname $0)/private && npm run docs:dev -- --port 3001"
echo ""
echo "终端3 - 学生知识库:"
echo "  cd $(dirname $0)/student && npm run docs:dev -- --port 3002"
echo ""
echo "终端4 - 家长知识库:"
echo "  cd $(dirname $0)/parent && npm run docs:dev -- --port 3003"
echo ""
echo "访问地址："
echo "  总站: http://localhost:3000"
echo "  个人: http://localhost:3001"
echo "  学生: http://localhost:3002"
echo "  家长: http://localhost:3003"
